#!/bin/bash
set -e
ROOTDIR=$(dirname "$0")
ROOTDIR=$(cd "$ROOTDIR/.." && pwd)
DOCKER_IMAGE_VERSION=$(cat "$ROOTDIR/shared/definitions/docker_image_version")
# shellcheck source=../shared/lib/library.sh
source "$ROOTDIR/shared/lib/library.sh"

for ARCH in amd64 arm64; do
    echo "phusion/passenger_binary_build_automation:$DOCKER_IMAGE_VERSION-$ARCH"
done
