#!/bin/bash
set -e
ROOTDIR=$(dirname "$0")
ROOTDIR=$(cd "$ROOTDIR/.." && pwd)
DOCKER_IMAGE_VERSION=$(cat "$ROOTDIR/shared/definitions/docker_image_version")
# shellcheck source=../shared/lib/library.sh
source "$ROOTDIR/shared/lib/library.sh"

run docker push "phusion/passenger_binary_build_automation_32:$DOCKER_IMAGE_VERSION"
run docker push "phusion/passenger_binary_build_automation_64:$DOCKER_IMAGE_VERSION"
