#!/bin/bash
set -e
ROOTDIR=$(dirname "$0")
ROOTDIR=$(cd "$ROOTDIR/.." && pwd)
DOCKER_IMAGE_VERSION=$(cat "$ROOTDIR/shared/definitions/docker_image_version")
# shellcheck source=../shared/lib/library.sh
source "$ROOTDIR/shared/lib/library.sh"

if [ "${GITHUB_ACTIONS}" = "true" ]; then
REGISTRY = "ghcr.io"
else
REGISTRY = "docker.io"
fi
BUILDBOX_NAME="$(REGISTRY)/phusion/passenger_binary_build_automation"

set -x
for ARCH in amd64 arm64; do
    docker buildx build --force-rm --pull \
	--platform "linux/$ARCH" \
	-t "$BUILDBOX_NAME:$DOCKER_IMAGE_VERSION-$ARCH" \
	-f "$ROOTDIR/linux/docker_image/Dockerfile" \
	"$ROOTDIR"
done
